#!/usr/local/bin/python
import urllib2, sys, socket, os

# url myIP
url = "http://www.meuip.com.br"

# hostname server
get_system = socket.gethostname()

# function to identify internet link outside.
def tbxEbt(url):
   print("outside %s " %(url))
   return

# connection number ESTABLISHED port deamon iwss (Trend Micro) example.: port 8080
def established(port):

   lsof = os.popen("sudo lsof -i:%s | grep ESTABLISHED" %(port))
   lines = len(lsof.readlines())
   lsof.close()
   return lines

# connection number CLOSE_WAIT port deamon iwss (Trend Micro) example.: port 8080
def close_wait(port):

   lsof = os.popen("sudo lsof -i:%s | grep CLOSE_WAIT" %(port))
   lines = len(lsof.readlines())
   lsof.close()
   return lines

# test dns resolver
def dns_resolver(host):
   try:
      resolver = 'DNS_OK ' + socket.gethostbyname(host)
   except:
      resolver = "::DNS Failed::"
   return resolver

# call functions
count_established = established(8080)
count_close_wait = close_wait(8080)
status_dns = dns_resolver(url)

# test access website to identify outside link
try:
   _Request = urllib2.Request(url)
   response = urllib2.urlopen(_Request)
   _Read = response.read()

# return exit code 2. CRITICAL
except:
   print("Error try to access website -- %s | DNS=%s;1;2;0;0 ESTABLISHED(8080)=%s CLOSE_WAIT(8080)=%s" %(dns_resolver(url),2,count_established,count_close_wait))
   sys.exit(2)

# find string provider internet link
if ("your provider ISP" in _Read):

   print("<your first provider ISP show here> (%s) %s| ESTABLISHED(8080)=%s CLOSE_WAIT(8080)=%s" %(get_system,status_dns,count_established,count_close_wait))
   sys.exit(0)

# find string provider internet link
elif ("your second provider ISP" in _Read):

   print("<your second provider ISP show here> (%s) %s| ESTABLISHED(8080)=%s CLOSE_WAIT(8080)=%s" %(get_system,status_dns,count_established,count_close_wait))
   sys.exit(1)
